version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./tinder-app
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    volumes:
      - ./tinder-app:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./tinder-app:/var/www
      - ./docker/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tinder_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge